### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Vizakenjack** [bitcoin-abe/bitcoin-abe#131]
Hello. I'm trying to run ABE with camcoin, but I got 403 error in the browser and this line in logs:

     [Wed Jul 16 12:51:18.942162 2014] [authz_core:error] [pid 16249:tid 140029649196800] [client 85.237.48.108:63264] AH01630: 
     client denied by server configuration: /usr/lib/cgi-bin/abe.fcgi

It's my ape.conf for apache:

    <VirtualHost *:80>
        ServerName camcoin.vzkj.ru
        Alias /static/ /var/www/bitcoin-abe/Abe/htdocs
        Alias /robots.txt /var/www/bitcoin-abe/Abe/htdocs/robots.txt
        Alias /favicon.ico /var/www/bitcoin-abe/Abe/htdocs/favicon.ico
        Alias / /usr/lib/cgi-bin/abe.fcgi/

        # Raise this if you get server errors mentioning "mod_fcgid:
        # read data timeout in 40 seconds"
        #FcgidIOTimeout 40

        # Uncomment to log Abe requests.
        ErrorLog /var/log/abe_error.log
        LogLevel info
        CustomLog /var/log/abe_access.log combined
    </VirtualHost>

**Comment by wargo32** [comment]
Execute
```bash
a2enmod cgi
```
and add
```apache
<Directory "PATH_TO_HTDOCS">
Require all granted
</Directory>
```
after (or everywhere in the same VirtualHost section)
```apache
Alias / /usr/lib/cgi-bin/abe.fcgi/
```
Then restart apache

**Comment by dermoth** [comment]
Closed; inactive and not Abe issue. If you have suggestion to enhance documentation please open a new issue.
