### ISSUE TITLE
Initial Data Load: "ImportError: No module named Crypto.Hash.SHA256"

### ISSUE THREAD

**Issue by jamwil** [bitcoin-abe/bitcoin-abe#159]
I've ran `pip install pycrypto` as well as `pip install Crypto` with no luck. I installed Abe with `python setup.py install` after configuring abe-sqlite.conf.

I know this is something trivial...
![screen shot 2015-01-13 at 11 45 02](https://cloud.githubusercontent.com/assets/424038/5726586/ba9687c8-9b19-11e4-80fe-63f1ff3a2e95.png)

**Comment by C1n** [comment]
I have the same issue. Installed pycrypto but still get the ImportError.

**Comment by v1nsai** [comment]
Worked for me on Linux after running `pip install Crypto`

Maybe something should be added to the documentation?

**Comment by ilovelinux** [comment]
> Worked for me on Linux after running `pip install Crypto`
I ran `pip install pycrypto` and it worked for me
Maybe these package are the same?
