### ISSUE TITLE
"address-history-rows-max"

### ISSUE THREAD

**Issue by everycrypto** [bitcoin-abe/bitcoin-abe#164]
it's is abilited with 
address-history-rows-max -1

not function:
http://explorer.winnerclubgnw.com:8080/address/FTbv6PRsT9nBMxkXh2x9FfNeQHhcWqgbjn

What should I do to make it work?

**Comment by K1773R** [comment]
dont set it to "unlimited" (even it dosnt work). this is a bad idea. rather set it to a high number (1000?)

**Comment by everycrypto** [comment]
yes of course
i have 2000 and 10000 too
another idea ?

**Comment by dermoth** [comment]
Did you restart your Webserver/FastCGI process after making the change?

If the webserver merely direct requests to a FastCGI process or Abe on its own then restarting the webserver is not enough, you have to restart the process running Abe.

**Comment by everycrypto** [comment]
thanks for the reply, I think it's the problem, because I have not done the re-start
you kindly tell me a web page / link where there is a written procedure for the restart?

**Comment by everycrypto** [comment]
file by modified are abe.py and not abe.conf
have setup at 3000
