### ISSUE TITLE
Raw genesis TX

### ISSUE THREAD

**Issue by Bushstar** [bitcoin-abe/bitcoin-abe#167]
Quick question I hope. How do you get the raw TX for the genesis_tx.py linked in below?

https://github.com/bitcoin-abe/bitcoin-abe/blob/master/Abe/genesis_tx.py

**Comment by jtobey** [comment]
If you run it in blkfile mode, and if it gets that far without an error, it logs the hex value for this purpose.  Otherwise, your best bet is a hex editor and any documentation you can find about the block format.

**Comment by Bushstar** [comment]
Thanks for responding. I got the genesis by loading the blkfile into a hex editor. Did not know that ABE logged that info.

We ran from blkfile but ran into two problems. Merkle mismatch on a block time after time and that the explorer only shows block 0.

Running from RPC we have further issues. Using the commit below to deal with the 0 block issue we get the error further below.

https://github.com/bitcoin-abe/bitcoin-abe/commit/829890b0c3bd2599e66108c24d90d16a5a1b0ea8

    python -m HTMLCoin-Abe.abe --config /home/explorer/HTMLCoinExplorer/HTMLCoin-Abe/abe-load.conf
    Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 9, 'loader': None, 'conf': None, 'dirname': u'/home/explorer/.HTML5', 'id': 23L}
    Traceback (most recent call last):
      File "HTMLCoin-Abe/DataStore.py", line 2770, in catch_up
    if not store.catch_up_rpc(dircfg):
      File "HTMLCoin-Abe/DataStore.py", line 2908, in catch_up_rpc
        assert rpc_hash == rpc_block['hash']
    AssertionError

Should I create a new issue for this?

**Comment by jtobey** [comment]
I wouldn't discourage you from creating an issue, but I no longer work on porting to new coins.

**Comment by hebs** [comment]
Did you ever figure this out? I am having the same problem. I get merkle root mismatch when running in blkfile mode, and assertion error running in rpc mode.
