### ISSUE TITLE
Help me ....

### ISSUE THREAD

**Issue by mayko20** [bitcoin-abe/bitcoin-abe#174]
1- the twistd -ny command launcher.tac reports an error downloading blockchain check last 30sec

2 - how to resolve this error my pool returns in the adm of page
     
      (We tried to poke your Stratum server using your $ config ['gettingstarted'] settings but it did not respond - Connection refused)

3 - how do I close the command twistd -y launcher.tac

**Comment by K1773R** [comment]
ABE is no pool.

**Comment by mayko20** [comment]
??
