### ISSUE TITLE
Remote MySQL - No joy :'(

### ISSUE THREAD

**Issue by AkiraTakizawa** [bitcoin-abe/bitcoin-abe#175]
Hello

I used to run bitcoin-abe successfully for almost a year on Amazon EC2 VPS (1vCPU, 1GB RAM, 10GB storage) with a local MySQL server. Because the VPS ran out of space and considering the costs to upgrade, I switched to another provider where I have a more powerful VPS (4 vCPU, 6GB RAM, 30GB SSD). As an extra, I got an offloaded MySQL database of 20GB.

I set up bitcoin-abe the same way I did at Amazon, except for the MySQL db and changed my configuration file accordingly:

```
datadir += [{
  "dirname":"/home/akira/.Minerals",
  "chain":"Mineralscoin"
}]
dbtype MySQLdb
connect-­args {"user":"x","host":"192.211.56.74","db":"mine1_abe","passwd":"x","port":3306}
upgrade
```

Unfortunately, this doesn't work at all :cry: 

```
python -m Abe.abe --config abe-min.conf --commit-bytes 100000 --no-serve

Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Reconnecting after rollback error: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
Reconnecting to database.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2101, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2095, in main
    store = make_store(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 159, in make_store
    store = DataStore.new(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 3277, in new
    return DataStore(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 187, in __init__
    store.initialize()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 629, in initialize
    store.configure()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 927, in configure
    config = store._sql.configure()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 614, in configure
    sql.configure_ddl_implicit_commit()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 699, in configure_ddl_implicit_commit
    if sql._test_ddl():
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 706, in _test_ddl
    sql.drop_table_if_exists("%stest_1" % sql.prefix)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 677, in drop_table_if_exists
    sql._drop_if_exists("TABLE", obj)
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 674, in _drop_if_exists
    sql.rollback()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 603, in rollback
    sql.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 292, in reconnect
    return sql.conn()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 275, in conn
    sql._conn = sql.connect()
  File "/usr/local/lib/python2.7/dist-packages/Abe/SqlAbstraction.py", line 233, in connect
    conn = sql.module.connect()
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

From what I understand, it still tries to connect to a local mysql server using unix sockets. Does it ignore the settings in the config file?

I forked bitcoin-abe in October last year: https://github.com/AkiraTakizawa/minerals-abe/commit/4ce5dc138470b81735eeddd25340ecfbe374fe09

**Comment by K1773R** [comment]
your not the only one. #168

**Comment by AkiraTakizawa** [comment]
Is there a problem with python-mysql maybe?

**Comment by AkiraTakizawa** [comment]
Problem solved!
```connect-args += {"host":"hostname or ip","user":"user","passwd":"password","db":"your db"}```

I simply added **+=**
Dev might want to update the documentation?

**Comment by dermoth** [comment]
This is strange; the option without `=` or `+=` should work too, and it does for me (both with default localhost and specific socket - I'm running 2 different mysqld's and can connect to both).

What if you use only `=` which should be more appropriate anyway? Do you have any other `connect-args` specified either in the file or on the command line??

**Comment by AkiraTakizawa** [comment]
Good morning

The option without ```=``` or ```+=``` does not work for me. Both ```=``` and ```+=``` work fine.
My .conf looks like this:
```
datadir += [{
  "dirname":"/home/akira/.Minerals",
  "chain":"Mineralscoin"
}]
dbtype=MySQLdb
connect-args += {"host":"daldb.vpsdime.com","user":"***","passwd":"***","db":"min_abe"}
upgrade
```
I will change ```+=``` to ```=```
It's hosted [here](http://explorer.morningminerals.com/chain/Mineralscoin)

**Comment by dermoth** [comment]
I tried the exact connect string you supplied that didn'T workl, replacing only the hostname. On paste there was a stace after the - oc conenct-args/

**Comment by dermoth** [comment]
I tried the exact connect string you supplied that didn't work, replacing only the hostname. On paste there was a space after the dash of connect-args, although we don't see it in your post. Can you confirm removing the `+=` now works? Make sure you edit the current line rather than commenting out or copying the old one.

**Comment by dermoth** [comment]
Just for clarification I think it's a unicode character, so it may show up differently based on the editor you use, but it's there.

**Comment by AkiraTakizawa** [comment]
Hello 

Here's a screenshot of what I see on the screen:
![vi](https://cloud.githubusercontent.com/assets/8864848/8395721/acaf1518-1d81-11e5-9cbb-81af0572ae18.PNG)

Using nano and vi, I see a space after the dash when connecting to the server using "Terminal" from KDE on OpenSUSE 13.2, which is kind of confusing. The screenshot here is made on a Windows 10 machine and it doesn't appear at all. Putty is configured to use UTF-8 on this machine. 
When editing it with nano or vi, there is no additional space. 

Normally OpenSUSE should also be configured as UTF-8.

**Comment by dermoth** [comment]
Ok, lets put it this way, if you edit your first post, put the cursor on connect-args, and walk around using the cursor keys, you will notice there is one hidden character after the dash (you have to press the arrow key twice to advance one visible character). I think your config without the `=` had this character, while the one with `=` or `+=` didn't, hence it worked not because of the `=` or `+=` but rather because of that extra character.

**Comment by AkiraTakizawa** [comment]
Hi. It's really strange, because I can't observe that kind of behaviour. I can't reproduce it either. I'm back on the PC which I used to write that. Maybe it's a Google Chrome quirck at the time of writing it? It got updated several times since then.

**Comment by dermoth** [comment]
Ok, can you just at least confirm you ran remove the = sign and it still works?

Either way i'll close this ticket as i'm pretty confident what happened at this point. The handling if unicode characters differs a lot between terminals, editors, etc.

Regards

**Comment by AkiraTakizawa** [comment]
I confirm that it works without = or += now:
The configuration file looks like:
```
datadir += [{
  "dirname":"/home/akira/.Minerals",
  "chain":"Mineralscoin"
}]
dbtype=MySQLdb
connect-args {"host":"daldb.vpsdime.com","user":"mine1_akira","passwd":"jcq7ha6l","db":"mine1_abe"}
upgrade

```
And I launched it with:
```
python -m Abe.abe --config abe-min-loader.conf --commit-bytes 100000 --no-serve
...
Opened /home/akira/.Minerals/blk0001.dat
block_tx 1905657 3830374
block_tx 1905657 3830375
block_tx 1905658 3830376
block_tx 1905658 3830377
commit
```
This time I puzzled about how I set it up before :open_mouth:
It wouldn't connect to the remote SQL at all, and now it just accepts it?

**Comment by dermoth** [comment]
The whole line was being ignored because it contained an "invisible" UTF8 characters right in the middle of `connect-args`.

This caused the driver to use the defaults so it tried connecting to the local socket.

Regards,

**Comment by AkiraTakizawa** [comment]
Something to keep in mind for the future when I bump again on this kind of error with other software. Thank you for looking into this (^_^)/
