### ISSUE TITLE
rpc_load: Imported mempool tx never cleaned up?

### ISSUE THREAD

**Issue by dermoth** [bitcoin-abe/bitcoin-abe#188]
Hi @jtobey,

I was fixing some issues with rpc loads when something occurred to me: the mempool tx we import doesn't seem to ever get cleaned up. I'm far from being as good as you in SQL, but is this query looking alright for finding them? (basically trying to find any `tx.tx_id` not referenced in `block_tx.tx_id`)

    SELECT COUNT(t.tx_id) FROM tx t LEFT JOIN block_tx b ON t.tx_id = b.tx_id WHERE b.tx_id IS NULL;

-- Update: Query above ran in ~2h30; queried all rows for both tables (>178M) and in my case returned 141k rows and counting (most of my data loads were historical data so no mempool involved). The difference between bitcoin tx count and max tx_id is likely the best approximation you can get for that number, assuming you haven't encountered too many chain reorgs).

Related questions about loading mempool tx... I've fixed an issue where we'd often thrown an RPC load failed on new blocks... now it looks like when we get to the end of mempool we should just load it up again (maybe with a 1sec sleep to avoid excessive looping if somehow the mempool is empty...). This may sound excessive but the advantage of that is that block load is much faster when you have all the tx already loaded (I've also saved us one useless SQL statement per tx already loaded in).

So I think we should:

1. Disable mempool loading by default. This is more consistent with the blockfile load method

2. When mempool loading is used, loop infinitely (i.e. don't need abe_loader anymore)

3. Eventually add a table to track mempool tx'es and clean them up after some time, or at the end of a full mempool run (although in my uncommitted code I break the loop whenever a new block is found). 

Schema change for `#3` would require querying up 89M+ rows for any tx not in block_tx (number based on tx count in bitcoin blockchain as of block heigh 380322, not counting lingering tx'es)

-----

Now the rest of this is totally unrelated, but since there is no mailing list or IRC I could use to start a discussion, I'm wondering how hard it would be to replace all the sequences/id PK's with hash indexes (binary or hex depending on config)... i.e. using block hash as PK for block, tx hash as PK for tx'es etc..

Most of the time spent loading blocks is looking up references. Tokudb is awesomely fast at loading data; looking it up, otoh, is like any other databases - it's only as fast as the underlying disks when the dataset doesn't fit in ram (Tokudb doesn't check FK references which is part of the speedup, but assuming bitcoin-core and abe don't do silly things consistency should be kept). 

If we managed to build a schema where all data from Bitcoin can be loaded straight up from blocks without any lookup besides previous block hash, load speed with Tokudb would be really awesome, even on slow disks.

**Comment by jtobey** [comment]
Yes, your query looks correct for finding transactions not in any block.  For the purpose of finding old mempool txs, I suggest creating a dummy block, e.g., block_id=-1, not in chain_candidate, and putting all mempool txs into it (via rows in block_tx).  The "cleanup" function then would iterate over tx in this "mempool block" and check whether each one is in any other block.  If it is in another block, remove it from the mempool block, otherwise decide whether to keep or purge it.

On using hash as primary key, it could help, but there are tradeoffs.  The 256-bit hash is larger than a sequence id and would be copied in block_tx, txin, txout, and various indexes, so the database size might grow.  You might use just some of the bits, but if you go too far, you risk collisions.  (Obviously, a subset of the block hash bits should avoid the leading zeroes.)

In my big redesign idea (which may never happen) Abe serves tx data from the block files directly, and block_id is a 64-bit value encoding blkfile number and offset.  Of course, I would have a uniqueness issue with any tx appearing in more than one block.

**Comment by dermoth** [comment]
`#1` & `#2` implemented in PR #189 if you wish to review/comment... otherwise i'll keep running it a couple days and merge if all looks good.

**Comment by dermoth** [comment]
@jtobey, I looked at using `block_tx`, the issue with it is that you have a constraint: `UNIQUE KEY `block_id` (`block_id`,`tx_pos`)`. This means I need to maintain an internal, artificial counter, and could also be an issue if a database has multiple chains (unless each chain has its own block).

If we really want to re-use a table, we could maybe use `block_txin` , but we'll get all inputs to link so probably a bad idea.

In the mean time I pushed more fixes to the PR...
- Use local time + option to set timezone (I hate it not seeing the same times as on the web & in my DB)
- Fix MySQL not doing string concats with `||` - use `CONCAT()` instead (upgrade to Abe40).
- Fix search for tx hashes not in the blockchain.

**Comment by dermoth** [comment]
Hi @jtobey,

If you have a few minutes please have a look at my attempt at tracking unlinked txins... I'm especially concerned about the cleanup code I came up with. See 388ac63 (it's in my cleean_mempool branch). I'm trying to clean up unused pubkeys after removing the txout items. it looks like pubkey_id is a reference to either a pubkey, or a multisig_pubkey, so I get a merged list of all pubkey/multisig child pubkey) and clean them up if they have no direct/indirect reference to the txout table.

I'm sure you'd come up with a better way to map out all multisig pubkeys anyway...

Before turning into a PR I still want to add the cleanup code to the mempool import logic

Also some earlier commits in that branch aren't yet in my current PR as I'm still testing them; especially the mempool loop issue; I'll need to encounter an orphan block to confirm it works...

**Comment by dermoth** [comment]
Landed in PR #198
