### ISSUE TITLE
YaCoin long int too large to convert to int

### ISSUE THREAD

**Issue by ghost** [bitcoin-abe/bitcoin-abe#19]
I tried to get Abe setup with YaCoin but it's ending up with a python error because of a overflow.

dash@rainbowdashh:~/src/yacoin-abe$ python -m Abe.abe --config abe.conf
ddl_implicit_commit=true
create_table_epilogue=''
max_varchar=4294967295
clob_type=CLOB
binary_type=buffer
int_type=str
Created silly table abe_dual
sequence_type=update
limit_style=native
Assigned chain_id 8 to YACoin
RPC failed: [Errno socket error] [Errno 111] Connection refused
catch_up_rpc: abort
Opened /home/dash/.yacoin/blk0001.dat
Exception at 72056512645693578
Failed to catch up {'blkfile_offset': 0, 'blkfile_number': 1, 'chain_id': 8, 'loader': None, 'dirname': u'/home/dash/.yacoin', 'id': 1}
Traceback (most recent call last):
  File "Abe/DataStore.py", line 2581, in catch_up
    store.catch_up_dir(dircfg)
  File "Abe/DataStore.py", line 2835, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "Abe/DataStore.py", line 2940, in import_blkdat
    b = store.parse_block(ds, chain_id, magic, length)
  File "Abe/DataStore.py", line 2971, in parse_block
    d['transactions'].append(deserialize.parse_Transaction(ds))
  File "Abe/deserialize.py", line 86, in parse_Transaction
    d['txIn'].append(parse_TxIn(vds))
  File "Abe/deserialize.py", line 45, in parse_TxIn
    d['sequence'] = vds.read_uint32()
  File "Abe/BCDataStream.py", line 71, in read_uint32
    def read_uint32(self): return self._read_num('<I')
  File "Abe/BCDataStream.py", line 110, in _read_num
    (i,) = struct.unpack_from(format, self.input, self.read_cursor)
OverflowError: long int too large to convert to int
Abe initialized.
Listening on http://0.0.0.0:2750

**Comment by dermoth** [comment]
This is a dup of #168 - it should be fixed already; please test and report any issue on the other issue.
