### ISSUE TITLE
Remove the blockfile loader

### ISSUE THREAD

**Issue by dermoth** [bitcoin-abe/bitcoin-abe#204]
The blockfile loader is no longer maintained. I don't have time nor enough hardware to test everything (my abe DB barely keeps up for now, and I doubt it will when block size increases), so I think it should be removed. Right now blocks gets in random order which causes lots of warnings at best, and if Bitcoind ever change the on-dick format again it will break anyway.

This issue it to get consensus on whenever I should go ahead with the removal. Anyone still using blkfile loader? Any reason they're not using RPC instead? This is now the time to voice your concerns.

Regards,

**Comment by K1773R** [comment]
I dont think it should be removed. Some old coins still depend on it. Yes i use it for some.

**Comment by dermoth** [comment]
Ok, then I guess one day we'll have to move loaders to standalone classes like the chains.

The root of the issue is the lack of development on Abe; I can barely keep it up with Bitcoin and IMHO the only way we can support altcoins right now is to have all other chain's code separate from Abe. This will let altchain developers implement/support their variant without the risk of breaking Bitcoin.

Out of curiosity which altcoins you know about doesn't support RPC loading? You know you have to enable tx indexes in bitcoin-core (or actually its altcoin fork) and re-index its database right?

**Comment by K1773R** [comment]
i didnt test a lot. it didnt work with: i0coin, ixcoin, bbqcoin, coiledcoin (very old), groupcoin (very old) and some others which i cant remember because i dropped them.

**Comment by dermoth** [comment]
For the heads up I now recommend blkfile for initial load anyway as rpc is way too slow on a fast disk... At least until I find a solution for RPC slowness.
