### ISSUE TITLE
Initial load using less than 5% of CPU. Is this by design?

### ISSUE THREAD

**Issue by llinfeng** [bitcoin-abe/bitcoin-abe#210]
I have started the initial load 5 days ago, and the initial load is not yet half-way through. I have tried everything I can hardware-wise, yet the CPU usage should drop after I have upgraded the RAM and hard drive.

I am using SQLite, on a Linux machine.

**Comment by K1773R** [comment]
Forget it! SQLite is heavy IO for disk. you'll be waiting for the disk forever. When loading, its mostly disk IO. Use a real db.

**Comment by llinfeng** [comment]
Thank you for the suggestion. What "real db" would you suggest? I am using Linux Mint as OS.

Yet, I checked my IO for the disk and found that it has also been under-used. I am using a SSD drive with SATA connection, and the max read/write speed shall be 100MB/s at minimum. Am I running the script wrong?
![image](https://cloud.githubusercontent.com/assets/5890407/20153828/8ec761a4-a692-11e6-88c2-9aa48f411304.png)

**Comment by K1773R** [comment]
Check the README-* files for other DBs, ie MYSQL and POSTGRES. You can use other DBs too, if you create a new wrapper.

**Comment by dermoth** [comment]
Also initial load should use the blockfile loader; rpc right now is very slow because it's done serially and we have to fetch separately the block header and each individual transaction.

There's also a lot of talks on database use in issue #207 

Regards

**Comment by coinflow** [comment]
The same here. With MariaDB, previously MySQL. Slow reaction of the system: it only uses 5-10% of the CPU and shows low disk I/O-rates. It's a server with low RAM/Memory, but the configuration is optimized for (e.g.: [performance_schema = off](https://mariadb.com/resources/blog/starting-mysql-low-memory-virtual-machines))

**Comment by llinfeng** [comment]
Hi @coinflow, for my particular case, it was not a DB-type problem, nor small RAM problem. Following exactly what the README file suggests for **initial loading** helped to boost my CPU usage from 5% to 100%:

* Improper command for initialization: `python -m Abe.abe --config abe-sqlite.conf`
* As suggested by the README: `python -m Abe.abe --config abe-sqlite.conf --commit-bytes 100000 --no-serve`

Then, controlling for DB-type (the little preferred SQLite), I am able to have my CPU run at 100% again. Also, using the "suggested" command for initializing the Database, I have achieved 100% usage of CPU with a 5 years old RAM of size 4GB.

Hope this would help.

**Comment by coinflow** [comment]
Hi @llinfeng,

thanks for the response. I'm using MariaDB with InnoDB, like recommended by @dermoth [here](https://github.com/bitcoin-abe/bitcoin-abe/issues/208). I'd like to try out SQLite also, in order to check, wheteher it could fit better on a smaller server, but when I start Abe with the settings for that, I get errors, like described in the linked thread.

**Comment by llinfeng** [comment]
@coinflow, I recently finished parsing the block chain into SQLite format last night. It took around 260GB of hard drive storage. Just a heads up. Good luck on your end!

**Comment by coinflow** [comment]
@llinfeng:
Here it's for an altcoin, so the database should not be that big. The blockchain itself has currently ~740 MB.

**Comment by coinflow** [comment]
What I have also seen is, that this slow behaviour is not all the time. It seems to depend on the blocks - maybe with certain addresses that have many txid's in them? The other blocks are intitialized much faster and then the CPU-consumption goes up to "even" 30-40% ...
Can someone shed some light on this?

**Comment by dermoth** [comment]
Are you running on Windows or Linux? On Linux, I haven't been able to open the SQLite database both for reading and writing (separate processes) except using libeatmydata (disables all data flushing and file locking, great for fast import but a powerfail or system crash could *destroy* your database).

Also 260GB for SQLite is *HUGE*, much more than InnoDB (171GB with recommended compression settings) and TokuDB (121GB, but doesn't check foreign key constraints, shouldn't be a big deal but could guard against some code bugs). I'd really like to know how much PostgreSQL take but I don't have the resources to run it.

Also SQLite had no support for binary storage (hashes have to be stored as TEXT, twice as much storage) and lacks support for large numeric values (some values will be stored as float instead leading to quite significant rounding drift over time).

**Comment by llinfeng** [comment]
I was running the commands as suggested in the `README-SQLITE.txt` as closely as I can, and the output (as of today) is 226 GB (just a correction). Once I have the time, I can go ahead and test out how much PostgreSQL shall take.

By the way, is there a good place to go for reference on the structure of the data-bases derived from Block-chains using `bitcoin-abe`? Sample code would be great.

**Comment by dermoth** [comment]
For the heads up, I mentioned rpc loading is very slow... The main reason was that it needed to fetch individual transactions in each block. As it turns out getblock defaults to verbose and turning it off allow getting full block data in a single RPC call!

Commit a974b8b in my fork does it; since we already had raw block decoding support for blockfile it was easy to implement it to the RPC loader.

The bottleneck now is back to Python, just like it was with plain blockfile import. It also remove the need for txindex=1 in bitcoind, at least without catch_up_mempool (for the latter I'll have to test.. I'm assuming at the very least we'll have to handle the case where the TX we're trying to load just made it to a block and is no longer accessible)

**Comment by coinflow** [comment]
@dermoth:
Only FYI: I'm using "default-loader = blkfile".
