### ISSUE TITLE
Denial of Service

### ISSUE THREAD

**Issue by Lvl4Sword** [bitcoin-abe/bitcoin-abe#214]
/chain/Your_Coin?count=1000000000
Causes Abe to quit, which makes the website broken

EDIT: It doesn't make Abe quit, it just uses a large amount of memory.
Which of course, can make Abe crash. :-)

**Comment by cuio** [comment]
how to solve this ?

**Comment by Lvl4Sword** [comment]
I've personally gone into abe.py and added this:

```
        if count >= 51:
            count = 1
```

below line 413 ( which is this ): 
> count = get_int_param(page, 'count') or 20
