### ISSUE TITLE
What version mysql use on windows ?

### ISSUE THREAD

**Issue by mraksoll** [bitcoin-abe/bitcoin-abe#222]
Reconnecting after rollback error: (2003, "Can't connect to MySQL server on 'loccalhost' (10061)")
what version of mysql use on windows for it's fucking start work.

I install mysql , i install connector on python , what need to do ? on linux same trash.

What version python use ? what version mysql use ? what version of connector use ?

**Comment by adityavichare** [comment]
Did you install mysqldb module?
https://pypi.python.org/pypi/MySQL-python
