### ISSUE TITLE
Failed: CREATE TABLE txout

### ISSUE THREAD

**Issue by Rsalazarm** [bitcoin-abe/bitcoin-abe#227]
Hello guys!

During the initial data load I have the following error:
Failed: CREATE TABLE txout (
    txout_id      NUMERIC(26) NOT NULL PRIMARY KEY,
    tx_id         NUMERIC(26) NOT NULL,
    txout_pos     NUMERIC(10) NOT NULL,
    txout_value   NUMERIC(30) NOT NULL,
    txout_scriptPubKey VARBINARY(1000000),
    pubkey_id     NUMERIC(26),
    UNIQUE (tx_id, txout_pos),
    FOREIGN KEY (pubkey_id)
        REFERENCES pubkey (pubkey_id)
)

Finally, the command stops with the following message:
_mysql_exceptions.OperationalError: (1074, "Column length too big for column 'txout_scriptPubKey' (max = 65535); use BLOB or TEXT instead")

I checked the issues reported and changed the max value to 65000 as suggested, but the problem is the same.

This is my abe-my.conf:
dbtype MySQLdb
connect-args {"user":"abe","db":"abe","passwd":"test","init_command":"SET defaul
t_storage_engine='InnoDB'","init_command":"SET NAMES binary"}
upgrade
port 2750

Any suggestion will be welcomed... ;)

Thanks in advance.

Ricardo.

**Comment by Rsalazarm** [comment]
No idea???

**Comment by dermoth** [comment]
My version of MySQL converts them directly to mediumblob... I assume yours doesn't.

As a quick fix, you can edit Abe/DataStore.py and change every occurrence of:

    VARBINARY(""" + str(MAX_SCRIPT) + """),

to:

     MEDIUMBLOB,

You can revert back after creating the database (run with `--no-load --no-serve` if you want to only create tables without loading anything into them).

Regards,

**Comment by dermoth** [comment]
Ohhh... There's clearly a bug even in my MySQL:

~~~
MariaDB [abe_test]> CREATE TABLE t1 (c1 VARBINARY(65532)); DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (1.95 sec)

Query OK, 0 rows affected (0.29 sec)

MariaDB [abe_test]> CREATE TABLE t1 (c1 VARBINARY(65533)); DROP TABLE IF EXISTS t1;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [abe_test]> CREATE TABLE t1 (c1 VARBINARY(65534)); DROP TABLE IF EXISTS t1;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [abe_test]> CREATE TABLE t1 (c1 VARBINARY(65535)); DROP TABLE IF EXISTS t1;
ERROR 1118 (42000): Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
Query OK, 0 rows affected, 1 warning (0.00 sec)

MariaDB [abe_test]> CREATE TABLE t1 (c1 VARBINARY(65536)); DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected, 1 warning (0.94 sec)

Query OK, 0 rows affected (0.14 sec)

MariaDB [abe_test]> 
~~~

MySQL seems to lie about maximum VARBINARY length but also fails to auto-convert it to BLOB. The warninbg I get on >65535:

~~~
+-------+------+-----------------------------------------------+
| Level | Code | Message                                       |
+-------+------+-----------------------------------------------+
| Note  | 1246 | Converting column 'c1' from VARBINARY to BLOB |
+-------+------+-----------------------------------------------+
~~~

**Comment by dermoth** [comment]
You may want to try my branch: https://github.com/dermoth/bitcoin-abe/tree/mysql_varbinary_fix

It should fix it for you

**Comment by dermoth** [comment]
@Rsalazarm, can you please confirm the branch fixes your issue?

Also out of curiosity what MySQL server version are you using?

Regards

**Comment by tamizharasank** [comment]
same error plz tell me a crct ansrrr
