### ISSUE TITLE
Cant get this to run at all 

### ISSUE THREAD

**Issue by izakhearn** [bitcoin-abe/bitcoin-abe#247]
This is my conf 

> dbtype MySQLdb
>     connect-args {"user":"abe","db":"abe","passwd":"pass"}
>     upgrade
>     port 2750
>     host 0.0.0.0
> 
> datadir += [{
> "dirname" : "/home/rhuskeeti/.keeti",
> "chain" : "Keeti",
> "loader": "rpc",
> "code3" : "KTC",
> "address_version" : "/u003c",
> "magic" : "u00fbu00c0u00b6u00db",
> "policy": "Sha256Chain"
> }]

and get the error 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 2114, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 2108, in main
    store = make_store(args)
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 156, in make_store
    store = DataStore.new(args)
  File "Abe/DataStore.py", line 3415, in new
    return DataStore(args)
  File "Abe/DataStore.py", line 211, in __init__
    store.init_chains()
  File "Abe/DataStore.py", line 491, in init_chains
    int(chain_decimals))
  File "Abe/Chain/__init__.py", line 21, in create
    mod = __import__(__name__ + '.' + policy, fromlist=[policy])
ImportError: No module named KEETI

```

**Comment by Lvl4Sword** [comment]
Did you create a custom chain in your local copy of https://github.com/bitcoin-abe/bitcoin-abe/tree/master/Abe/Chain ?

**Comment by izakhearn** [comment]
No i have not

**Comment by Lvl4Sword** [comment]
That's why you're getting the error. Try that and see if you get an error after that.

**Comment by izakhearn** [comment]
Sorry to ask how do i do that

**Comment by Lvl4Sword** [comment]
https://github.com/bitcoin-abe/bitcoin-abe/blob/master/Abe/Chain/Bitcoin.py has things that you'll need to add into a Keeti.py in Abe/Chain

```
from .Sha256Chain import Sha256Chain

class Keeti(Sha256Chain):
    def __init__(chain, **kwargs):
        chain.name = 'Keeti'
        chain.code3 = 'KTC'
        chain.address_version = '' # whatever the address version is for this coin
        chain.script_addr_vers = '' # same with this
        chain.magic = '' # place u00fbu00c0u00b6u00db here
Sha256Chain.__init__(chain, **kwargs)
```

**Comment by izakhearn** [comment]
Okay did that still getting the same error

**Comment by Lvl4Sword** [comment]
Change your .conf to the following:

```
dbtype MySQLdb
connect-args {"user":"abe","db":"abe","passwd":"password"}
upgrade
port 2750

datadir += [{
        "dirname": "/home/rhuskeeti/.keeti",
        "chain": "Keeti",
        "code3": "KTC",
        "address_version": "\u003c"
      }]
```

and paste your traceback

**Comment by izakhearn** [comment]
```
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 2114, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 2108, in main
    store = make_store(args)
  File "/home/rhuskeeti/Desktop/bitcoin-abe/Abe/abe.py", line 156, in make_store
    store = DataStore.new(args)
  File "Abe/DataStore.py", line 3415, in new
    return DataStore(args)
  File "Abe/DataStore.py", line 211, in __init__
    store.init_chains()
  File "Abe/DataStore.py", line 491, in init_chains
    int(chain_decimals))
  File "Abe/Chain/__init__.py", line 21, in create
    mod = __import__(__name__ + '.' + policy, fromlist=[policy])
ImportError: No module named KEETI

```

**Comment by Lvl4Sword** [comment]
Have you created Abe/Chain/Keeti.py with that information I gave you?

**Comment by izakhearn** [comment]
Yes i did

**Comment by izakhearn** [comment]
I even tried to compile it now to see if that works

**Comment by izakhearn** [comment]
Tried Every thing from the start still getting that error

**Comment by vm06007** [comment]
I have the same error

**Comment by vm06007** [comment]
root@wolf424:/# sudo python -m Abe.abe --config abe-my.conf --commit-bytes 100000 --no-serve
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2114, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 2108, in main
    store = make_store(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/abe.py", line 156, in make_store
    store = DataStore.new(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 3415, in new
    return DataStore(args)
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 211, in __init__
    store.init_chains()
  File "/usr/local/lib/python2.7/dist-packages/Abe/DataStore.py", line 491, in init_chains
    int(chain_decimals))
  File "/usr/local/lib/python2.7/dist-packages/Abe/Chain/__init__.py", line 21, in create
    mod = __import__(__name__ + '.' + policy, fromlist=[policy])
ImportError: No module named Fenix

**Comment by vm06007** [comment]
ok creating the .py file as instructed did solve the problem for me, but I have now a bit different issue -> 
![screen shot 2018-02-14 at 6 17 29 pm](https://user-images.githubusercontent.com/1138692/36199088-7697f0b6-11b3-11e8-845a-847bfb824e8d.JPG)

I'm not sure why it tries to open bitcoin.conf instead of fenix.conf in ./fenix directory although even if I create bitcoin.conf with same content as fenix.conf I get similar error

**Comment by vm06007** [comment]
@dermoth is this related to segwit?

**Comment by Lvl4Sword** [comment]
@vm06007 Don't run as root or sudo and paste a traceback

@izakhearn Can you try again from a clean install? What SQL DB are you using?

**Comment by dermoth** [comment]
This looks like the kind of error you'd get trying to decode segwit transactions...

Maybe it would work from my segwit branch, but it will still miss the witness information.... I can't guarantee it will work as well as a with a pre-segwit bitdoind though, even if it doesn't crash it could be missing some information that gets canned by bitcoind for old clients when it strips the witness part. I can't recall exactly.

**Comment by err0r3o3** [comment]
@vm06007 
try to add:
          "conf": "fenix.conf",
to your conf

**Comment by bitcoinstant** [comment]
it's like if you don't do it from a clean install at first and you screw up, there is no going back.  cmon guys, figure this out. something is appending when it should be overwriting.

**Comment by dermoth** [comment]
There should be no need to go from a clean install unless:

1. something got badly corrupt outside of Abe's control
2. Configuration got changed in a way that is incompatible (ex binary vs hex storage for hashes, scriptsig storage...) If you want to write conversion script you're welcome, but this is a volunteer-run project with not much active developers anymore (I cannot run the Bitcoin blockchain on my hardware anymore so I don't have much interest in keeping it up anymore anyway... OTOH I do watch Ppull requests and approve them when they look OK)

Regards,

**Comment by bitcoinstant** [comment]
>  OTOH I do watch pull requests and approve them when they look OK)


Good to know!  Cheers! :)
