### ISSUE TITLE
Unable to read any Abe tables in mysql

### ISSUE THREAD

**Issue by jsdantony** [bitcoin-abe/bitcoin-abe#265]
Hi there,

I am new to crypto and programming. So I am not sure if this is really an issue.

I am unable read the table from abe mysql database,

The 'pubkey' table looks like this,
![screenshot_001](https://user-images.githubusercontent.com/38221066/38508053-7dcdd8ae-3c61-11e8-8a59-ec97abcca1b3.JPG)

The 'block' table looks like this,
![image](https://user-images.githubusercontent.com/38221066/38508161-bc8eff0a-3c61-11e8-9461-dbf53358fdfc.png)

Abe works fine (everything is readable) in the web interface, although little slow. Hence I was trying view tables directly in mysql, but they are totally unreadable. My first guess was it was in wrong characterset, but I am not sure how to fix this.

Am I missing something !? is there any query to fix this.

Appreciate your help in advance.

regards,
Antony

**Comment by Lvl4Sword** [comment]
Is this Bitcoin or some other coin? How did you set it up to begin with?

**Comment by jsdantony** [comment]
This is Bitcoin indeed. I followed the instruction in Abe 'README.md' and 'README-MYSQL.md'.
- Installed Python 2.7.12, pycrypto2.6.1 and python-mysqldb
- Installed mysql  Ver 14.14 Distrib 5.7.11
- created abe database and created abe user.
- Installed Bitcoin-Abe with 'python setup.py install'
- updated 'abe-my.conf' to bitcoin blocks folder
- Ran the initial data load with 'python -m Abe.abe --config abe-my.conf --commit-bytes 100000 --no-serve'
- After a week of initial load ran 'python -m Abe.abe --config myconf.conf'

everything seemed to loading and working fine in web interface, except for the weird characters in backend tables. 

I did cross check the character set, it seems to be created with mysql default 'latin1' and collation 'latin1_swedish_ci'. I did ran a new instance with a new database with utf8mb4 format, the result was still unreadable (though different from latin1).

I don't believe I used any compression for tables.
do let me know if I have missed anything.


Appreciate your help

**Comment by dermoth** [comment]
The binary data is stored in binary form - this is the most compact representation and data size matters a lot for most people....

You can either convert to hex on read (ex. `SELECT pubkey_id, HEX(pubkey_hash), HEX(pubkey) FROM pubkey LIMIT 100;`) or re-import the data with binary storage turned off (you will suffer approx 30% increase in database size IIRC); see abe.conf for configuration details.
