### ISSUE TITLE
bitcoinabe stops at block 163392

### ISSUE THREAD

**Issue by codygroup** [bitcoin-abe/bitcoin-abe#266]
I am new to bitcoinabe and I have it set up on a computer.

The initial run took weeks and now when I look at bitcoinabe it shows the last block as 163392 and does not show any more than that, nor will it allow me to search an blocks after that.

I looked at the database in phpmyadmin and there are many more blocks in the database.

I did notice that chain_last_block_id was 163729 and referenced 163392 as the last block under Bitcoin.

Did I do something wrong?

Thanks in advance.

Mark

**Comment by codygroup** [comment]
I tried running it again after cleaning out the sql database and it stopped at the same spot.

It turns out the bitcoind had one block file that must have been corrupted as I got the chain again and it has gone past that point.

Now I have a few weeks to go again.

**Comment by Lvl4Sword** [comment]
I'm glad you figured out what the issue was :+1:
