### ISSUE TITLE
Bitcoin -ABE

### ISSUE THREAD

**Issue by immense055** [bitcoin-abe/bitcoin-abe#279]
Can I you different wallet in my account like hithub,blockchain or other

**Comment by dermoth** [comment]
This sentence makes no sense and this is an issue tracker, not Q&A forum. You can join #bitcoin-abe on Freenode to ask questions.

**Comment by immense055** [comment]
Yes iwant to join #bitcoin-abe on freenode.
How I setup #bitcoin-abe use

**Comment by immense055** [comment]
Yes iwant to join #bitcoin-abe on freenode.
How I setup #bitcoin-abe use

**Comment by Lvl4Sword** [comment]
Please don't double post the same thing.
Go to https://webchat.freenode.net/ and put in your username/password and #bitcoin-abe as the channel

**Comment by immense055** [comment]
Boss how can I get #bitcoin-abe the channel

**Comment by Lvl4Sword** [comment]
1. Go to https://webchat.freenode.net/
2. You'll see ``Nickname:`` and an input box - put your nickname here
3. You'll see ``Channels:`` and an input box - put #bitcoin-abe here
4. Click the box next to ``I'm not a robot`` and complete the captcha.
5. Hit the ``Connect`` submit button.
6. You're in the channel.

**Comment by immense055** [comment]
What is marser HEAD???

**Comment by Lvl4Sword** [comment]
Hop back into the IRC and we can answer your questions. This is for issues with Bitcoin-Abe, not a Q&A session.
