### ISSUE TITLE
How much longer do I have left?any plans for a progress bar in the future?

### ISSUE THREAD

**Issue by WesNz** [bitcoin-abe/bitcoin-abe#280]
Hi!

Installed bitcoin-abe and bitcoin core.... Everything went great until the mysql import part.

Is there any way of speeding this up? On server grade equipment with ssd's...currently it's day 3 now.

The server CPU and ram is hardly doing anything during the import... how can I increase anything or everything to speed this import process up?

My current status:

block_tx 192160 5586293
block_tx 192160 5586294
block_tx 192160 5586295
block_tx 192160 5586296
block_tx 192160 5586297
block_tx 192160 5586298
block_tx 192160 5586299
block_tx 192160 5586300
block_tx 192160 5586301
block_tx 192160 5586302
block_tx 192160 5586303

**Comment by WesNz** [comment]
All good. I managed to speed this import process quite quickly with a few changes.
:)

**Comment by Lvl4Sword** [comment]
What were the changes you applied?

**Comment by fields** [comment]
I've also had this problem on postgres - it's been running for two weeks and it's only up to 2015. @WesNz what changes did you make?

**Comment by yiwc** [comment]
How long will it take now I guess 200 days？

**Comment by dermoth** [comment]
FYI OP mentioned mysql... My best guess is that he's tuned some stuff properly or enabled binary storage, but it won't help for long unless he's got the hardware to keep it fast.

Every block, transaction, tx input and output has to be indexed with a sequence and those sequences needs to be discovered by looking up secondary keys. This makes loading large blocks very slow. Before I stopped running a Bitcoin explorer the only way I could keep up was to constantly import mempool transactions so when the block arrived most tx'es were already there...

IMHO the only was import could be fast, for Abe or its successor, will be to index blocks and transactions using their hashes so we can do a blind import. Then after that there are many way to speed up even further bulk imports.

**Comment by dermoth** [comment]
Also progress bar would not be very very accurate without looking at actual transaction count and inputs/outputs count (closest approximation maybe would be block size....). First few years of bitcoin import is lightning fast, then completely slow down. Segwit probably exacerbates this as it increases the actual block size (just not to the view of non-segwit nodes, so it's not a hard fork). It's not really worth it anyway.
