### ISSUE TITLE
DataStore MerkleRootMismatch Issue

### ISSUE THREAD

**Issue by Lvl4Sword** [bitcoin-abe/bitcoin-abe#295]
Within the following: https://github.com/woodcoin-core/woodcoin-explorer/blob/791c037aea71f019095482068b0de53d739bef7a/Abe/DataStore.py#L1086

there's essentially:
https://github.com/bitcoin-abe/bitcoin-abe/blob/b10c01b6378d2765348ad2828c28e163e71efe74/Abe/DataStore.py#L1088-L1091

Full traceback:
```py
Traceback (most recent call last):
  File "/home/user/abe/Abe/DataStore.py", line 2566, in catch_up
    store.catch_up_dir(dircfg)
  File "/home/user/abe/Abe/DataStore.py", line 2857, in catch_up_dir
    store.import_blkdat(dircfg, ds, blkfile['name'])
  File "/home/user/abe/Abe/DataStore.py", line 2989, in import_blkdat
    store.import_block(b, chain = chain)
  File "/home/user/abe/Abe/DataStore.py", line 1096, in import_block
    raise MerkleRootMismatch(b['hash'], tx_hash_array)
Abe.DataStore.MerkleRootMismatch: Block header Merkle root does not match its transactions. block hash=b'14508459b221041eab257d2baaa7459775ba748246c8403609eb708f0e57e74b'
```

the MerkleRootMismatch gets raised every time Bitcoin-Abe starts when the system reboots.
b['hashMerkleRoot'] is always 64 '\x00' as well.

I initially thought this wasn't an issue, but it obviously is if it's causing an error.

Probably missing something basic here, and could be a difference between bytes / strings.

Would love another set of eyes on this so I can get a Flask version of Abe out quicker for this repo.

Printing these:
```py
print(hashPrev)
print(b['hashMerkleRoot'])
print(tx_hash_array)
print(chain.merkle_root(tx_hash_array))
print(chain.genesis_hash_prev)
```

gives me the following:
```text
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
[]
[]
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```

Found out the issue. ``prev_out`` failed when https://github.com/bitcoin-abe/bitcoin-abe/blob/d33f6e85de74e708e11cabe4ed0246e12025c726/Abe/SqlAbstraction.py#L77-78 was called , which gave ``LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs``, and turned prev_out to ``None``!

**Comment by dermoth** [comment]
So..... Anything that needs fixing? was the null prev_out saved to the database or was is just a run-time error?

**Comment by Lvl4Sword** [comment]
I've been working on the Flask rework, and will circle back to this if it's still an issue then.
