### ISSUE TITLE
error in parsing blocks?

### ISSUE THREAD

**Issue by yakitorifoodie** [bitcoin-abe/bitcoin-abe#298]
I'm using mysql and tried the below commands to verify but i see only scrambled data.

https://imgur.com/a/RerOxqC

**Comment by dermoth** [comment]
The data is saved in binary form. To see proper data, you will have to hex-encode it. Instead of `SELECT *`  you will have to specify all fields and encoders, ex:

    SELECT block_id, HEX(block_hash), [...] FROM block LIMIT 5;

Storing binary data in binary form instead of hex saves about 50% of storage for these binary fields.
