### ISSUE TITLE
Does Abe depend on Python3.8?

### ISSUE THREAD

**Issue by aa1756349463** [bitcoin-abe/bitcoin-abe#302]
Although I installed it, there were some syntax errors on the control side.
Then I checked the code in Pycharm and found some syntax errors, such as "long_value = 0L" in base58.py.， "execfile("Abe/version.py")" in setup.py, which is also a syntax error. I changed it to "exec(open("Abe/version.py", encoding ='utf-8').read())" so that it can be installed. I am wondering if it is the reason why I use python3.8 version.
;
;
;Is there any kind person who can answer my question? That person must be very handsome

**Comment by Lvl4Sword** [comment]
Bitcoin-Abe depends on Python 2 ( Yes, even though Python 2 has been EOL since January 1st ). Have you taken a look at https://github.com/woodcoin-core/woodcoin-explorer ? That'll be what I'd recommend working on until my Flask fork/rework is complete.

**Comment by aa1756349463** [comment]
thank u very much

**Comment by dermoth** [comment]
It's stuck in python2 world and conversion would be quite hard. A modern replacement is in the works, search for CryptoCurrencyExplorer...
