### ISSUE TITLE
The LTC address got wrong.

### ISSUE THREAD

**Issue by Geraek** [bitcoin-abe/bitcoin-abe#307]
How can i contract you ? 
my Bitcoin address same as bitcoin-abe address Litecoin please help.

**Comment by Geraek** [comment]
please help my actual address Litecoin: MUmYCV8oALW2LiUuq9TtY3JgxNu7do7BHs

**Comment by Lvl4Sword** [comment]
I'm not sure what you mean.
Is this related to Bitcoin-Abe? Is this a Litecoin-specific wallet/program issue?

**Comment by Geraek** [comment]
I forgot change wallet when withdraw

**Comment by Geraek** [comment]
it is LTC wallet not bitcoin.

**Comment by Geraek** [comment]
Can you help me sent it back to my wallet it literally for LTC: MUmYCV8oALW2LiUuq9TtY3JgxNu7do7BHs
BTC: 3HH8Cv4afouFAKdJmR2v2f5dHyHCYpbUXq

**Comment by Lvl4Sword** [comment]
Wallet issues aren't within scope of Bitcoin-Abe, and we can't assist you with that.
Bitcoin-Abe is an explorer which shows information about the blockchain(s).
I'm going to go ahead and close this, since there's nothing we can do here.

**Comment by dermoth** [comment]
@Geraek indeed we cannot help, but if you're able to understand how addresses relate to private keys and you have a valid private key for the "wrong" address you sent the fund to, you may be able to generate and import the corresponding private address and reclaim the funds (ex under a BIP32 scheme each network has a fixed value to make addresses unique, and it may be possible to manually force generating a private address for the correct network and reclaim the funds).

Addresses also have some validations in them, and I would be surprised if you managed to make it send funds to an totally invalid address, although it's possible to do so... If you somehow did the funds are lost forever.

So if you cannot clearly understand what you did (and from your earlier explanation it's not even clear to me what you did), your best option is fo find someone who can and who can be trusted, and see if it's possible to create a private wallet address to reclaim the funds.
