### ISSUE TITLE
How big is the database size currently in 2022 for Bitcoin?

### ISSUE THREAD

**Issue by cercos** [bitcoin-abe/bitcoin-abe#312]
I see an older post from around 2017 or so that said the DB was ~110GB.  I would imagine that has doubled in size if not tripled?  I'm on 1.75 days of this parsing  and it's at 110GB.  There's about 300GB left on the drive and  I just want to make sure it's going to be enough.

**Comment by LeadManPL** [comment]
@cercos It was over 400GB for me few months ago. I assume it would be 500GB now

**Comment by Lvl4Sword** [comment]
I'm unsure as to the size. I've been working on https://github.com/cryptocurrencyexplorer/cryptocurrencyexplorer and would suggest development time/effort be put towards that.
