### ISSUE TITLE
Add bitcoin as a topic to this repository

### ISSUE THREAD

**Issue by gourcetools** [bitcoin-abe/bitcoin-abe#315]
Hello,

This repository is listed on the [Awesome Bitcoin](https://raw.githubusercontent.com/igorbarinov/awesome-bitcoin/master/README.md) list, which is a collection of useful Bitcoin projects. However, it seems that the 'bitcoin' topic is missing from this repository's topics.

Adding the 'bitcoin' topic will help users discover your project more easily and recognize its relevance to the Bitcoin ecosystem. To add the topic, please follow these steps:

1. Navigate to the main page of the repository.
2. Click on the gear icon next to "About" on the right side of the page.
3. In the "Topics" section, type 'bitcoin' and press Enter.
4. Click "Save changes."

Thank you for your attention and for contributing to the Bitcoin community!

**Comment by Lvl4Sword** [comment]
Seeing as this project uses Python 2, isn't actively supported and hasn't been for a while.

**Comment by gourcetools** [comment]
wut ? should i remove it from awesome bitcoin?
why not just add topic or archive?

**Comment by Lvl4Sword** [comment]
That's up to you. There's work being done on another project ( https://github.com/CryptocurrencyExplorer/CryptocurrencyExplorer ), but it's still a work in progress and isn't ready for prime-time.

In regards to adding the topic, that would probably bring more eyes to Abe.
Which isn't the best idea, considering folks will probably use it in production, and that's not a great idea at this point.

Archiving might be an option, but @dermoth would need to sign off on that as well.

**Comment by gourcetools** [comment]
Gotcha, this was automated. Sorry to bother you guys.
